---
collections:
  - name: community.general
    version: ">=3.0.0"
  - name: ansible.posix
    version: ">=1.0.0"

# ansible.cfg mejorado
[defaults]
inventory = inventory/hosts.ini
roles_path = roles
host_key_checking = false
timeout = 30
forks = 5
gather_facts = true
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible_facts_cache
fact_caching_timeout = 86400

[inventory]
enable_plugins = host_list, script, auto, yaml, ini, toml

[privilege_escalation]
become = true
become_method = sudo
become_user = root
become_ask_pass = false