---
- name: Basic setup on all servers
  hosts: all
  become: yes
  roles:
    - common

- name: Install InfluxDB
  hosts: influxdb
  become: yes
  roles:
    - influxdb

- name: Install Telegraf on servers
  hosts: telegraf_servers
  become: yes
  roles:
    - telegraf

- name: Install Node Exporter
  hosts: node_exporter_servers
  become: yes
  roles:
    - node_exporter

- name: Install Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus

- name: Verify services
  hosts: all
  tasks:
    - name: Check that the services are running
      uri:
        url: "{{ item }}"
        method: GET
      ignore_errors: yes
      loop:
        - "http://{{ ansible_default_ipv4.address }}:{{ prometheus_port }}"
        - "http://{{ ansible_default_ipv4.address }}:{{ influxdb_port }}/ping"
        - "http://{{ ansible_default_ipv4.address }}:{{ node_exporter_port }}/metrics"
      when: item != ""
