---
- name: Common setup
  hosts: all
  become: yes
  roles:
    - common
  tags:
    - common

- name: Deploy Telegraf
  hosts: telegraf_servers
  become: yes
  roles:
    - telegraf
  tags:
    - telegraf

- name: Deploy Node Exporter
  hosts: exporter_servers
  become: yes
  roles:
    - node_exporter
  tags:
    - node_exporter

- name: Deploy Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
  tags:
    - prometheus

- name: Deploy Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags:
    - grafana

- name: Verify deployment
  hosts: all
  become: yes
  tasks:
    - name: Check service status
      systemd:
        name: "{{ item }}"
      register: service_status
      loop:
        - telegraf
        - node_exporter
        - prometheus
        - grafana-server
      when: item in group_names
      tags:
        - verify