---
- name: restart influxdb
  block:

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      when: ansible_service_mgr == 'systemd'

    - name: Restart influxdb.service
      systemd:
        name: influxdb
        state: restarted
        enabled: yes
      when: ansible_service_mgr == 'systemd'

    - name: Launch influxd manually in background (Docker fallback)
      shell: |
        pkill influxd || true
        nohup influxd --config /etc/influxdb/influxdb.conf \
          > /var/log/influxd.log 2>&1 &
      args:
        executable: /bin/bash
      when: ansible_service_mgr != 'systemd'
