---
- name: restart influxdb
  block:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart influxdb.service
      systemd:
        name: influxdb
        state: restarted

    - name: Restart InfluxDB manually (Docker fallback)
      shell: |
        pkill influxd || true
        nohup influxd --config /etc/influxdb/influxdb.conf \
          > /var/log/influxd.log 2>&1 &
      args:
        executable: /bin/bash
      when: ansible_service_mgr != 'systemd'
  when: ansible_service_mgr == 'systemd' or ansible_service_mgr != 'systemd'