- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - wget
      - curl
      - unzip
      - htop
      - vim
    state: present

- name: Configure timezone
  timezone:
    name: "{{ timezone | default('UTC') }}"