---
- name: restart prometheus
  block:

    - name: Reload systemd
      systemd:
        daemon_reload: yes
      when: ansible_service_mgr == 'systemd'

    - name: Restart prometheus service
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
      when: ansible_service_mgr == 'systemd'

    - name: Launch prometheus manually (Docker fallback)
      shell: |
        pkill prometheus || true
        nohup prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.path=/var/lib/prometheus \
          > /var/log/prometheus.log 2>&1 &
      args:
        executable: /bin/bash
      when: ansible_service_mgr != 'systemd'
